import Head from "next/head";
import {Inter} from "@next/font/google";
import Header from "../components/Header";
import Hero from "../components/Hero";
import About from "../components/About";
import Experience from "../components/Experience";
import Skills from "../components/Skills";

const inter = Inter({subsets: ["latin"]});

export default function Home() {
  return (
    <div className='bg-primary text-white min-h-screen snap-y snap-mandatory overflow-scroll z-0'>
      <Head>
        <title>My Portfolio</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header />

      <section id='hero' className='snap-start'>
        <Hero />
      </section>

      <section id='about' className='snap-center'>
        <About />
      </section>

      <section id='experience' className='snap-center'>
        <Experience />
      </section>

      <section id='skills' className='snap-start'>
        <Skills />
      </section>

      {/* PROJECTS */}
      {/* CONTACT ME */}
    </div>
  );
}
