import Head from "next/head";
import {Inter} from "@next/font/google";
import Header from "../components/Header";
import Hero from "../components/Hero";

const inter = Inter({subsets: ["latin"]});

export default function Home() {
  return (
    <div className='bg-primary text-white min-h-screen snap-y snap-mandatory overflow-scroll z-0'>
      <Head>
        <title>My Portfolio</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      {/* HERO */}
      <section id='hero' className='snap-center'>
        <Hero />
      </section>
      {/* ABOUT */}
      {/* EXPERIENCES */}
      {/* SKILLS */}
      {/* PROJECTS */}
      {/* CONTACT ME */}
    </div>
  );
}
